/*------------------------------------------------------------*/
/*   Esquema para a criação do banco de dados da aplicação    */
/*                        PortalDefault                       */
/*------------------------------------------------------------*/
/*                                                            */
/*   IMPORTANTE: Este schema usa TIMESTAMPTZ para todos os   */
/*   campos de data/hora, garantindo suporte a timezone.     */
/*   Configure o banco para timezone UTC:                    */
/*   ALTER DATABASE seu_banco SET timezone TO 'UTC';         */
/*                                                            */
/*------------------------------------------------------------*/
/*                     Exclusão de Views                      */
/*------------------------------------------------------------*/

/*------------------------------------------------------------*/
/*                     Exclusão de tabelas                    */
/*------------------------------------------------------------*/

DROP TABLE IF EXISTS "erp"."tb_account";
DROP TABLE IF EXISTS "erp"."tb_account_payable_receivable";
DROP TABLE IF EXISTS "erp"."tb_company";
DROP TABLE IF EXISTS "erp"."tb_company_setting";
DROP TABLE IF EXISTS "erp"."tb_company_user";
DROP TABLE IF EXISTS "erp"."tb_contract";
DROP TABLE IF EXISTS "erp"."tb_contract_benefit_discount";
DROP TABLE IF EXISTS "erp"."tb_contract_cost_center";
DROP TABLE IF EXISTS "erp"."tb_cost_center";
DROP TABLE IF EXISTS "erp"."tb_employee";
DROP TABLE IF EXISTS "erp"."tb_employee_allowed_location";
DROP TABLE IF EXISTS "erp"."tb_financial_transaction";
DROP TABLE IF EXISTS "erp"."tb_justification";
DROP TABLE IF EXISTS "erp"."tb_loan_advance";
DROP TABLE IF EXISTS "erp"."tb_location";
DROP TABLE IF EXISTS "erp"."tb_payroll";
DROP TABLE IF EXISTS "erp"."tb_payroll_employee";
DROP TABLE IF EXISTS "erp"."tb_payroll_item";
DROP TABLE IF EXISTS "erp"."tb_purchase_order";
DROP TABLE IF EXISTS "erp"."tb_role";
DROP TABLE IF EXISTS "erp"."tb_task";
DROP TABLE IF EXISTS "erp"."tb_task_comment";
DROP TABLE IF EXISTS "erp"."tb_task_employee";
DROP TABLE IF EXISTS "erp"."tb_task_status_history";
DROP TABLE IF EXISTS "erp"."tb_time_entry";
DROP TABLE IF EXISTS "erp"."tb_transaction_cost_center";
DROP TABLE IF EXISTS "erp"."tb_user";
DROP TABLE IF EXISTS "erp"."tb_user_token";
/*------------------------------------------------------------*/
/*                     Criação das tabelas                    */
/*------------------------------------------------------------*/

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_account       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_account"(
	"account_id"                           bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"account_name"                         varchar (255)        NOT NULL,
	"account_type"                         varchar (10)         NOT NULL,
	"account_initial_balance"              decimal (15,2)       DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_account" PRIMARY KEY 
		(
			"account_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*                erp.tb_account_payable_receivable                */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_account_payable_receivable"(
	"account_payable_receivable_id"        bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"supplier_customer_id"                 bigint               NULL,
	"account_payable_receivable_description" varchar (255)        NOT NULL,
	"account_payable_receivable_type"      varchar (10)         NOT NULL,
	"account_payable_receivable_amount"    decimal (15,2)       DEFAULT 0 NOT NULL,
	"account_payable_receivable_due_date"  date                 NOT NULL,
	"account_payable_receivable_is_paid"   boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_account_payable_receivable" PRIMARY KEY 
		(
			"account_payable_receivable_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_company       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_company"(
	"company_id"                           bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_name"                         varchar (255)        NOT NULL,
	"company_document"                     varchar (14)         NULL,
	"user_id"                              bigint               DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
	"deletado_em"                          timestamptz          NULL,
	"deletado_por"                         bigint               NULL,
		CONSTRAINT "pk_company" PRIMARY KEY 
		(
			"company_id"
		) 
);
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*           erp.tb_company_setting           */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_company_setting"(
	"company_setting_id"                   bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"employee_id_general_manager"          bigint               NULL,
	"company_setting_time_tolerance_minutes" bigint               DEFAULT 0 NOT NULL,
	"company_setting_payroll_day"          bigint               DEFAULT 0 NOT NULL,
	"company_setting_payroll_closing_day"  bigint               DEFAULT 0 NOT NULL,
	"company_setting_vacation_days_per_year" bigint               DEFAULT 0 NOT NULL,
	"company_setting_min_hours_for_lunch_break" decimal (4,2)        DEFAULT 0 NOT NULL,
	"company_setting_max_overtime_hours_per_month" decimal (5,2)        DEFAULT 0 NOT NULL,
	"company_setting_allow_weekend_work"   boolean              NOT NULL,
	"company_setting_require_justification_after_hours" bigint               DEFAULT 0 NOT NULL,
	"company_setting_weekly_hours_default" decimal (5,2)        DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_company_setting" PRIMARY KEY 
		(
			"company_setting_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*         erp.tb_company_user         */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_company_user"(
	"company_user_id"                      bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"user_id"                              bigint               DEFAULT 0 NOT NULL,
	"role_id"                              bigint               NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_company_user" PRIMARY KEY 
		(
			"company_user_id"
		) 
);

ALTER TABLE "erp"."tb_company_user" ADD CONSTRAINT "uk_company_user_company_user" UNIQUE("company_id","user_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_contract       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_contract"(
	"contract_id"                          bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"contract_type"                        varchar (10)         NOT NULL,
	"contract_value"                       decimal (10,2)       DEFAULT 0 NOT NULL,
	"contract_is_payroll"                  boolean              NOT NULL,
	"contract_has_inss"                    boolean              NOT NULL,
	"contract_has_irrf"                    boolean              NOT NULL,
	"contract_has_fgts"                    boolean              NOT NULL,
	"contract_start_date"                  date                 NOT NULL,
	"contract_end_date"                    date                 NULL,
	"contract_weekly_hours"                bigint               NULL,
	"contract_is_active"                   boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_contract" PRIMARY KEY 
		(
			"contract_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*                erp.tb_contract_benefit_discount                */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_contract_benefit_discount"(
	"contract_benefit_discount_id"         bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"contract_id"                          bigint               DEFAULT 0 NOT NULL,
	"contract_benefit_discount_description" varchar (255)        NOT NULL,
	"contract_benefit_discount_type"       varchar (10)         NOT NULL,
	"contract_benefit_discount_application" varchar (10)         NOT NULL,
	"contract_benefit_discount_amount"     decimal (10,2)       DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_contract_benefit_discount" PRIMARY KEY 
		(
			"contract_benefit_discount_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*             erp.tb_contract_cost_center             */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_contract_cost_center"(
	"contract_cost_center_id"              bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"contract_id"                          bigint               DEFAULT 0 NOT NULL,
	"cost_center_id"                       bigint               DEFAULT 0 NOT NULL,
	"contract_cost_center_percentage"      decimal (5,2)        DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_contract_cost_center" PRIMARY KEY 
		(
			"contract_cost_center_id"
		) 
);

ALTER TABLE "erp"."tb_contract_cost_center" ADD CONSTRAINT "uk_contract_cost_center_contract_cost_center" UNIQUE("contract_id","cost_center_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*         erp.tb_cost_center         */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_cost_center"(
	"cost_center_id"                       bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"cost_center_name"                     varchar (255)        NOT NULL,
	"cost_center_description"              text                 NULL,
	"cost_center_is_active"                boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_cost_center" PRIMARY KEY 
		(
			"cost_center_id"
		) 
);

ALTER TABLE "erp"."tb_cost_center" ADD CONSTRAINT "uk_cost_center_company_name" UNIQUE("company_id","cost_center_name");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_employee       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_employee"(
	"employee_id"                          bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"user_id"                              bigint               NULL,
	"employee_id_manager"                  bigint               NULL,
	"employee_nickname"                    varchar (100)        NOT NULL,
	"employee_full_name"                   varchar (255)        NOT NULL,
	"employee_email"                       varchar (255)        NOT NULL,
	"employee_phone"                       varchar (20)         NOT NULL,
	"employee_cpf"                         varchar (11)         NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
	"employee_profile_image"               BYTEA                NULL,
		CONSTRAINT "pk_employee" PRIMARY KEY 
		(
			"employee_id"
		) 
);

ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "uk_employee_cpf" UNIQUE("employee_cpf");
ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "uk_employee_email" UNIQUE("employee_email");
ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "uk_employee_nickname" UNIQUE("company_id","employee_nickname");
ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "uk_employee_phone" UNIQUE("employee_phone");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*                erp.tb_employee_allowed_location                */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_employee_allowed_location"(
	"employee_allowed_location_id"         bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"location_id"                          bigint               NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_employee_allowed_location" PRIMARY KEY 
		(
			"employee_allowed_location_id"
		) 
);

ALTER TABLE "erp"."tb_employee_allowed_location" ADD CONSTRAINT "uk_employee_allowed_location_employee_location" UNIQUE("employee_id","location_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*              erp.tb_financial_transaction              */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_financial_transaction"(
	"financial_transaction_id"             bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"account_id"                           bigint               DEFAULT 0 NOT NULL,
	"purchase_order_id"                    bigint               NULL,
	"account_payable_receivable_id"        bigint               NULL,
	"supplier_customer_id"                 bigint               NULL,
	"loan_advance_id"                      bigint               NULL,
	"financial_transaction_description"    varchar (255)        NOT NULL,
	"financial_transaction_type"           varchar (10)         NOT NULL,
	"financial_transaction_amount"         decimal (15,2)       DEFAULT 0 NOT NULL,
	"financial_transaction_transaction_date" date                 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_financial_transaction" PRIMARY KEY 
		(
			"financial_transaction_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*          erp.tb_justification          */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_justification"(
	"justification_id"                     bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"justification_reference_date"         date                 NOT NULL,
	"justification_reason"                 text                 NOT NULL,
	"justification_attachment_url"         varchar (2048)       NULL,
	"justification_hours_granted"          decimal (5,2)        NULL,
	"user_id_approver"                     bigint               NULL,
	"justification_status"                 varchar (10)         NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_justification" PRIMARY KEY 
		(
			"justification_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*         erp.tb_loan_advance         */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_loan_advance"(
	"loan_advance_id"                      bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"loan_advance_amount"                  decimal (10,2)       DEFAULT 0 NOT NULL,
	"loan_advance_installments"            bigint               DEFAULT 0 NOT NULL,
	"loan_advance_discount_source"         varchar (10)         NOT NULL,
	"loan_advance_start_date"              date                 NOT NULL,
	"loan_advance_is_approved"             boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_loan_advance" PRIMARY KEY 
		(
			"loan_advance_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_location       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_location"(
	"location_id"                          bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"location_name"                        varchar (255)        NOT NULL,
	"location_address"                     text                 NULL,
	"location_latitude"                    decimal (9,6)        DEFAULT 0 NOT NULL,
	"location_longitude"                   decimal (9,6)        DEFAULT 0 NOT NULL,
	"location_radius_meters"               bigint               DEFAULT 0 NOT NULL,
	"location_is_active"                   boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_location" PRIMARY KEY 
		(
			"location_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*       erp.tb_payroll       */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_payroll"(
	"payroll_id"                           bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"payroll_period_start_date"            date                 NOT NULL,
	"payroll_period_end_date"              date                 NOT NULL,
	"payroll_total_gross_pay"              decimal (15,2)       DEFAULT 0 NOT NULL,
	"payroll_total_deductions"             decimal (15,2)       DEFAULT 0 NOT NULL,
	"payroll_total_net_pay"                decimal (15,2)       DEFAULT 0 NOT NULL,
	"payroll_is_closed"                    boolean              NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_payroll" PRIMARY KEY 
		(
			"payroll_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*           erp.tb_payroll_employee           */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_payroll_employee"(
	"payroll_employee_id"                  bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"payroll_id"                           bigint               DEFAULT 0 NOT NULL,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"payroll_employee_is_on_vacation"      boolean              NOT NULL,
	"payroll_employee_vacation_days"       bigint               NULL,
	"payroll_employee_vacation_advance_amount" decimal (10,2)       NULL,
	"payroll_employee_total_gross_pay"     decimal (10,2)       DEFAULT 0 NOT NULL,
	"payroll_employee_total_deductions"    decimal (10,2)       DEFAULT 0 NOT NULL,
	"payroll_employee_total_net_pay"       decimal (10,2)       DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_payroll_employee" PRIMARY KEY 
		(
			"payroll_employee_id"
		) 
);

ALTER TABLE "erp"."tb_payroll_employee" ADD CONSTRAINT "uk_payroll_employee_payroll_employee" UNIQUE("payroll_id","employee_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*         erp.tb_payroll_item         */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_payroll_item"(
	"payroll_item_id"                      bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"payroll_employee_id"                  bigint               DEFAULT 0 NOT NULL,
	"payroll_item_description"             varchar (255)        NOT NULL,
	"payroll_item_type"                    varchar (10)         NOT NULL,
	"payroll_item_category"                varchar (10)         NOT NULL,
	"payroll_item_amount"                  decimal (10,2)       DEFAULT 0 NOT NULL,
	"payroll_item_reference_id"            bigint               NULL,
	"payroll_item_calculation_basis"       decimal (10,2)       NULL,
	"payroll_item_calculation_details"     jsonb                NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_payroll_item" PRIMARY KEY 
		(
			"payroll_item_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*          erp.tb_purchase_order          */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_purchase_order"(
	"purchase_order_id"                    bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"user_id_requester"                    bigint               DEFAULT 0 NOT NULL,
	"user_id_approver"                     bigint               NULL,
	"purchase_order_description"           text                 NOT NULL,
	"purchase_order_total_amount"          decimal (15,2)       DEFAULT 0 NOT NULL,
	"purchase_order_status"                varchar (10)         NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_purchase_order" PRIMARY KEY 
		(
			"purchase_order_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*     erp.tb_role     */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_role"(
	"role_id"                              bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"role_name"                            varchar (255)        NOT NULL,
	"role_permissions"                     jsonb                NOT NULL,
	"role_is_system"                       boolean              DEFAULT false NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_role" PRIMARY KEY 
		(
			"role_id"
		) 
);

ALTER TABLE "erp"."tb_role" ADD CONSTRAINT "uk_role_company_name" UNIQUE("company_id","role_name");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*     erp.tb_supplier_customer     */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_supplier_customer"(
	"supplier_customer_id"                 bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"supplier_customer_name"               varchar (255)        NOT NULL,
	"supplier_customer_document"           varchar (14)         NULL,
	"supplier_customer_email"              varchar (255)        NULL,
	"supplier_customer_phone"              varchar (20)         NULL,
	"supplier_customer_address"            text                 NULL,
	"supplier_customer_is_active"          boolean              DEFAULT true NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_supplier_customer" PRIMARY KEY 
		(
			"supplier_customer_id"
		) 
);

ALTER TABLE "erp"."tb_supplier_customer" ADD CONSTRAINT "uk_supplier_customer_company_name" UNIQUE("company_id","supplier_customer_name");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*     erp.tb_task     */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_task"(
	"task_id"                              bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"company_id"                           bigint               DEFAULT 0 NOT NULL,
	"task_id_parent"                       bigint               NULL,
	"task_id_blocking"                     bigint               NULL,
	"task_title"                           varchar (255)        NOT NULL,
	"task_description"                     text                 NULL,
	"task_priority"                        varchar (10)         NOT NULL,
	"task_frequency_days"                  bigint               NULL,
	"task_allow_sunday"                    boolean              NOT NULL,
	"task_allow_monday"                    boolean              NOT NULL,
	"task_allow_tuesday"                   boolean              NOT NULL,
	"task_allow_wednesday"                 boolean              NOT NULL,
	"task_allow_thursday"                  boolean              NOT NULL,
	"task_allow_friday"                    boolean              NOT NULL,
	"task_allow_saturday"                  boolean              NOT NULL,
	"task_start_date"                      date                 NULL,
	"task_end_date"                        date                 NULL,
	"task_overall_status"                  varchar (10)         NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_task" PRIMARY KEY 
		(
			"task_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*         erp.tb_task_comment         */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_task_comment"(
	"task_comment_id"                      bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"task_id"                              bigint               DEFAULT 0 NOT NULL,
	"user_id"                              bigint               DEFAULT 0 NOT NULL,
	"task_comment_comment"                 text                 NOT NULL,
	"task_comment_attachment_url"          varchar (2048)       NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_task_comment" PRIMARY KEY 
		(
			"task_comment_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*          erp.tb_task_employee          */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_task_employee"(
	"task_employee_id"                     bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"task_id"                              bigint               DEFAULT 0 NOT NULL,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"task_employee_status"                 varchar (10)         NOT NULL,
	"task_employee_estimated_hours"        decimal (10,2)       NULL,
	"task_employee_actual_hours"           decimal (10,2)       NULL,
	"task_employee_start_date"             timestamptz          NULL,
	"task_employee_end_date"               timestamptz          NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_task_employee" PRIMARY KEY 
		(
			"task_employee_id"
		) 
);

ALTER TABLE "erp"."tb_task_employee" ADD CONSTRAINT "uk_task_employee_task_employee" UNIQUE("task_id","employee_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*             erp.tb_task_status_history             */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_task_status_history"(
	"task_status_history_id"               bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"task_employee_id"                     bigint               DEFAULT 0 NOT NULL,
	"task_status_history_old_status"       varchar (10)         NULL,
	"task_status_history_new_status"       varchar (10)         NOT NULL,
	"task_status_history_change_reason"    text                 NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_task_status_history" PRIMARY KEY 
		(
			"task_status_history_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*        erp.tb_time_entry        */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_time_entry"(
	"time_entry_id"                        bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"employee_id"                          bigint               DEFAULT 0 NOT NULL,
	"time_entry_type"                      varchar (10)         NOT NULL,
	"time_entry_timestamp"                 timestamptz          NOT NULL,
	"time_entry_latitude"                  decimal (9,6)        NULL,
	"time_entry_longitude"                 decimal (9,6)        NULL,
	"location_id"                          bigint               NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_time_entry" PRIMARY KEY 
		(
			"time_entry_id"
		) 
);

/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*               erp.tb_transaction_cost_center               */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_transaction_cost_center"(
	"transaction_cost_center_id"           bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"financial_transaction_id"             bigint               DEFAULT 0 NOT NULL,
	"cost_center_id"                       bigint               DEFAULT 0 NOT NULL,
	"transaction_cost_center_amount"       decimal (15,2)       DEFAULT 0 NOT NULL,
	"transaction_cost_center_percentage"   decimal (5,2)        DEFAULT 0 NOT NULL,
	"criado_por"                           bigint               DEFAULT 0 NOT NULL,
	"atualizado_por"                       bigint               NULL,
	"criado_em"                            timestamptz          DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"atualizado_em"                        timestamptz          NULL,
		CONSTRAINT "pk_transaction_cost_center" PRIMARY KEY 
		(
			"transaction_cost_center_id"
		),
		CONSTRAINT "chk_transaction_cost_center_percentage" CHECK (transaction_cost_center_percentage >= 0 AND transaction_cost_center_percentage <= 100)
);

ALTER TABLE "erp"."tb_transaction_cost_center" ADD CONSTRAINT "uk_transaction_cost_center_transaction_cost_center" UNIQUE("financial_transaction_id","cost_center_id");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*     erp.tb_user     */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_user"(
	"user_id"                              bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"user_email"                           varchar (255)        NULL,
	"user_phone"                           varchar (20)         NULL,
	"user_cpf"                             varchar (11)         NULL,
	"user_password_hash"                   varchar (255)        NOT NULL,
	"user_reset_token"                     varchar (2048)       NULL,
	"user_reset_token_expires_at"          timestamptz          NULL,
		CONSTRAINT "pk_user" PRIMARY KEY 
		(
			"user_id"
		) ,
		CONSTRAINT "ck_user_at_least_one_contact" CHECK (
    		(user_cpf IS NOT NULL AND LENGTH(TRIM(user_cpf)) >= 11) OR 
    		(user_email IS NOT NULL AND LENGTH(TRIM(user_email)) >= 5) OR 
    		(user_phone IS NOT NULL AND LENGTH(TRIM(user_phone)) >= 8)
		)
);

ALTER TABLE "erp"."tb_user" ADD CONSTRAINT "uk_user_cpf" UNIQUE("user_cpf");
ALTER TABLE "erp"."tb_user" ADD CONSTRAINT "uk_user_email" UNIQUE("user_email");
ALTER TABLE "erp"."tb_user" ADD CONSTRAINT "uk_user_phone" UNIQUE("user_phone");
/*------------------------------------------------------------*/
/*    Criação de Tabelas, Indices e Atribuição de Default    */
/*        erp.tb_user_token        */
/*------------------------------------------------------------*/

 CREATE TABLE "erp"."tb_user_token"(
	"user_token_id"                        bigint               NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	"user_id"                              bigint               DEFAULT 0 NOT NULL,
	"user_token_token"                     varchar (2048)       NOT NULL,
	"user_token_refresh_token"             varchar (2048)       NULL,
	"user_token_expires_at"                timestamptz          NOT NULL,
	"user_token_refresh_expires_at"        timestamptz          NULL,
	"user_token_is_revoked"                boolean              NOT NULL,
		CONSTRAINT "pk_user_token" PRIMARY KEY 
		(
			"user_token_id"
		) 
);

ALTER TABLE "erp"."tb_user_token" ADD CONSTRAINT "uk_user_token_refresh_token" UNIQUE("user_token_refresh_token");
ALTER TABLE "erp"."tb_user_token" ADD CONSTRAINT "uk_user_token_token" UNIQUE("user_token_token");

/*------------------------------------------------------------*/
/*                     Índices                                */
/*------------------------------------------------------------*/

-- Índice para melhorar performance de queries que filtram empresas não deletadas
CREATE INDEX "idx_company_deletado_em" ON "erp"."tb_company"("deletado_em");

/*------------------------------------------------------------*/
/*                 Constraints de Foreign Key                */
/*------------------------------------------------------------*/

ALTER TABLE "erp"."tb_account" ADD CONSTRAINT "fk_account_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_account_payable_receivable" ADD CONSTRAINT "fk_account_payable_receivable_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_account_payable_receivable" ADD CONSTRAINT "fk_account_payable_receivable_supplier_customer"
	FOREIGN KEY
		("supplier_customer_id")
	REFERENCES "erp"."tb_supplier_customer"
		("supplier_customer_id");

ALTER TABLE "erp"."tb_company_setting" ADD CONSTRAINT "fk_company_setting_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_company_user" ADD CONSTRAINT "fk_company_user_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_company_user" ADD CONSTRAINT "fk_company_user_role"
	FOREIGN KEY
		("role_id")
	REFERENCES "erp"."tb_role"
		("role_id");

ALTER TABLE "erp"."tb_company_user" ADD CONSTRAINT "fk_company_user_user"
	FOREIGN KEY
		("user_id")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_contract" ADD CONSTRAINT "fk_contract_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_contract_benefit_discount" ADD CONSTRAINT "fk_contract_benefit_discount_contract"
	FOREIGN KEY
		("contract_id")
	REFERENCES "erp"."tb_contract"
		("contract_id");

ALTER TABLE "erp"."tb_contract_cost_center" ADD CONSTRAINT "fk_contract_cost_center_contract"
	FOREIGN KEY
		("contract_id")
	REFERENCES "erp"."tb_contract"
		("contract_id");

ALTER TABLE "erp"."tb_contract_cost_center" ADD CONSTRAINT "fk_contract_cost_center_cost_center"
	FOREIGN KEY
		("cost_center_id")
	REFERENCES "erp"."tb_cost_center"
		("cost_center_id");

ALTER TABLE "erp"."tb_cost_center" ADD CONSTRAINT "fk_cost_center_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "fk_employee_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "fk_employee_employee_manager"
	FOREIGN KEY
		("employee_id_manager")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_employee" ADD CONSTRAINT "fk_employee_user"
	FOREIGN KEY
		("user_id")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_employee_allowed_location" ADD CONSTRAINT "fk_employee_allowed_location_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_employee_allowed_location" ADD CONSTRAINT "fk_employee_allowed_location_location"
	FOREIGN KEY
		("location_id")
	REFERENCES "erp"."tb_location"
		("location_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_account"
	FOREIGN KEY
		("account_id")
	REFERENCES "erp"."tb_account"
		("account_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_account_payable_receivable"
	FOREIGN KEY
		("account_payable_receivable_id")
	REFERENCES "erp"."tb_account_payable_receivable"
		("account_payable_receivable_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_purchase_order"
	FOREIGN KEY
		("purchase_order_id")
	REFERENCES "erp"."tb_purchase_order"
		("purchase_order_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_supplier_customer"
	FOREIGN KEY
		("supplier_customer_id")
	REFERENCES "erp"."tb_supplier_customer"
		("supplier_customer_id");

ALTER TABLE "erp"."tb_financial_transaction" ADD CONSTRAINT "fk_financial_transaction_loan_advance"
	FOREIGN KEY
		("loan_advance_id")
	REFERENCES "erp"."tb_loan_advance"
		("loan_advance_id")
	ON DELETE CASCADE;

ALTER TABLE "erp"."tb_justification" ADD CONSTRAINT "fk_justification_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_justification" ADD CONSTRAINT "fk_justification_user_approver"
	FOREIGN KEY
		("user_id_approver")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_loan_advance" ADD CONSTRAINT "fk_loan_advance_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_location" ADD CONSTRAINT "fk_location_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_payroll" ADD CONSTRAINT "fk_payroll_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_payroll_employee" ADD CONSTRAINT "fk_payroll_employee_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_payroll_employee" ADD CONSTRAINT "fk_payroll_employee_payroll"
	FOREIGN KEY
		("payroll_id")
	REFERENCES "erp"."tb_payroll"
		("payroll_id");

ALTER TABLE "erp"."tb_payroll_item" ADD CONSTRAINT "fk_payroll_item_payroll_employee"
	FOREIGN KEY
		("payroll_employee_id")
	REFERENCES "erp"."tb_payroll_employee"
		("payroll_employee_id");

ALTER TABLE "erp"."tb_purchase_order" ADD CONSTRAINT "fk_purchase_order_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_purchase_order" ADD CONSTRAINT "fk_purchase_order_user_approver"
	FOREIGN KEY
		("user_id_approver")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_purchase_order" ADD CONSTRAINT "fk_purchase_order_user_requester"
	FOREIGN KEY
		("user_id_requester")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_supplier_customer" ADD CONSTRAINT "fk_supplier_customer_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_task" ADD CONSTRAINT "fk_task_company"
	FOREIGN KEY
		("company_id")
	REFERENCES "erp"."tb_company"
		("company_id");

ALTER TABLE "erp"."tb_task" ADD CONSTRAINT "fk_task_task_blocking"
	FOREIGN KEY
		("task_id_blocking")
	REFERENCES "erp"."tb_task"
		("task_id");

ALTER TABLE "erp"."tb_task" ADD CONSTRAINT "fk_task_task_parent"
	FOREIGN KEY
		("task_id_parent")
	REFERENCES "erp"."tb_task"
		("task_id");

ALTER TABLE "erp"."tb_task_comment" ADD CONSTRAINT "fk_task_comment_task"
	FOREIGN KEY
		("task_id")
	REFERENCES "erp"."tb_task"
		("task_id");

ALTER TABLE "erp"."tb_task_comment" ADD CONSTRAINT "fk_task_comment_user"
	FOREIGN KEY
		("user_id")
	REFERENCES "erp"."tb_user"
		("user_id");

ALTER TABLE "erp"."tb_task_employee" ADD CONSTRAINT "fk_task_employee_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_task_employee" ADD CONSTRAINT "fk_task_employee_task"
	FOREIGN KEY
		("task_id")
	REFERENCES "erp"."tb_task"
		("task_id");

ALTER TABLE "erp"."tb_task_status_history" ADD CONSTRAINT "fk_task_status_history_task_employee"
	FOREIGN KEY
		("task_employee_id")
	REFERENCES "erp"."tb_task_employee"
		("task_employee_id");

ALTER TABLE "erp"."tb_time_entry" ADD CONSTRAINT "fk_time_entry_employee"
	FOREIGN KEY
		("employee_id")
	REFERENCES "erp"."tb_employee"
		("employee_id");

ALTER TABLE "erp"."tb_time_entry" ADD CONSTRAINT "fk_time_entry_location"
	FOREIGN KEY
		("location_id")
	REFERENCES "erp"."tb_location"
		("location_id");

ALTER TABLE "erp"."tb_transaction_cost_center" ADD CONSTRAINT "fk_transaction_cost_center_cost_center"
	FOREIGN KEY
		("cost_center_id")
	REFERENCES "erp"."tb_cost_center"
		("cost_center_id");

ALTER TABLE "erp"."tb_transaction_cost_center" ADD CONSTRAINT "fk_transaction_cost_center_transaction"
	FOREIGN KEY
		("financial_transaction_id")
	REFERENCES "erp"."tb_financial_transaction"
		("financial_transaction_id");

ALTER TABLE "erp"."tb_user_token" ADD CONSTRAINT "fk_user_token_user"
	FOREIGN KEY
		("user_id")
	REFERENCES "erp"."tb_user"
		("user_id");

