-- Migration: Alterações de Ordem de Compra e Configurações da Empresa
-- Data: 2026-01-19

-- ===========================================
-- 1. Alterações na tabela tb_purchase_order
-- ===========================================

-- Adicionar coluna account_id
ALTER TABLE erp.tb_purchase_order 
ADD COLUMN IF NOT EXISTS account_id BIGINT NULL;

-- Adicionar coluna processed_message
ALTER TABLE erp.tb_purchase_order 
ADD COLUMN IF NOT EXISTS purchase_order_processed_message TEXT NULL;

-- Adicionar coluna processed_at
ALTER TABLE erp.tb_purchase_order 
ADD COLUMN IF NOT EXISTS purchase_order_processed_at TIMESTAMPTZ NULL;

-- Alterar tamanho do campo status (de varchar(10) para varchar(20))
ALTER TABLE erp.tb_purchase_order 
ALTER COLUMN purchase_order_status TYPE VARCHAR(20);

-- Adicionar FK para account_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_purchase_order_account'
    ) THEN
        ALTER TABLE erp.tb_purchase_order 
        ADD CONSTRAINT fk_purchase_order_account
        FOREIGN KEY (account_id) REFERENCES erp.tb_account(account_id);
    END IF;
END $$;

-- ===========================================
-- 2. Nova tabela tb_default_cost_center_distribution
-- ===========================================

CREATE TABLE IF NOT EXISTS erp.tb_default_cost_center_distribution (
    default_cost_center_distribution_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT DEFAULT 0 NOT NULL,
    cost_center_id BIGINT NOT NULL,
    default_cost_center_distribution_percentage DECIMAL(5,2) NOT NULL,
    criado_por BIGINT DEFAULT 0 NOT NULL,
    atualizado_por BIGINT NULL,
    criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMPTZ NULL,
    CONSTRAINT pk_default_cost_center_distribution PRIMARY KEY (default_cost_center_distribution_id)
);

-- Unique constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uk_default_cc_dist_company_cost_center'
    ) THEN
        ALTER TABLE erp.tb_default_cost_center_distribution 
        ADD CONSTRAINT uk_default_cc_dist_company_cost_center 
        UNIQUE (company_id, cost_center_id);
    END IF;
END $$;

-- FK para company_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_default_cc_dist_company'
    ) THEN
        ALTER TABLE erp.tb_default_cost_center_distribution 
        ADD CONSTRAINT fk_default_cc_dist_company
        FOREIGN KEY (company_id) REFERENCES erp.tb_company(company_id) ON DELETE CASCADE;
    END IF;
END $$;

-- FK para cost_center_id
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_default_cc_dist_cost_center'
    ) THEN
        ALTER TABLE erp.tb_default_cost_center_distribution 
        ADD CONSTRAINT fk_default_cc_dist_cost_center
        FOREIGN KEY (cost_center_id) REFERENCES erp.tb_cost_center(cost_center_id) ON DELETE CASCADE;
    END IF;
END $$;
